name: Build UsbDk Driver

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Windows Driver Kit (WDK)
      run: |
        choco install wdk --yes
        refreshenv
        
    - name: Clone UsbDk repository
      run: |
        git clone https://github.com/daynix/UsbDk.git
        
    - name: Build UsbDk
      working-directory: ./UsbDk
      run: |
        .\buildAll.bat Release
        
    - name: Upload UsbDk driver artifacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: usbdk-artifacts
        path: ./UsbDk/UsbDk/Build/Driver/Win10/x64/Release
