name: Build UsbDk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Install CMake
      uses: lukka/get-cmake@v3.29.6

    - name: Install NuGet
      run: choco install nuget

    - name: Restore NuGet packages
      run: nuget restore UsbDk.sln

    - name: Configure with CMake
      run: cmake -Bbuild -H. -G "Visual Studio 16 2019" -A x64

    - name: Build with MSBuild
      run: msbuild build/UsbDk.sln /p:Configuration=Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: UsbDk
        path: build/Release
