name: Build Windows Driver

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up MSVC environment
      uses: microsoft/setup-msbuild@v1
      
    - name: Install Windows Driver Kit (WDK)
      run: |
        choco install wdk --yes
        refreshenv
        
    - name: Build driver
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64 UsbDk.sln
        
    - name: Upload driver artifacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: driver-artifacts
        path: path/to/your/driver/artifacts
