name: Build UsbDk Driver

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.1.0

    - name: Install Windows 10 SDK
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        with:
          sdk-version: 20348

    - name: Install WDK 10
      run: |
        choco install windows-driver-kit

    - name: Install WiX Toolset
      run: |
        choco install wixtoolset

    - name: Set up WiX Toolset path
      run: |
        $env:Path += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"
        echo "::add-path::C:\Program Files (x86)\WiX Toolset v3.11\bin"

    - name: Build UsbDk project
      run: |
        msbuild UsbDk.sln /p:Configuration=Release /p:Platform=x64

    - name: Create MSI installer
      run: |
        candle.exe path\to\UsbDk.wxs
        light.exe path\to\UsbDk.wixobj -o path\to\output\UsbDk.msi

    - name: Upload MSI
      uses: actions/upload-artifact@v2
      with:
        name: UsbDk-installer
        path: path\to\output\UsbDk.msi
